classregister/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'classregister'

urlpatterns = [
    path('list/', views.class_list, name='list'),                                  #클래스리스트
    path('<int:class_id>/', views.detail, name='detail'),                          #클래스상세
    path('register/', views.register, name='register'),                            #클래스등록
    path('classupdate/<int:class_id>/', views.classupdate, name='classupdate'),    #클래스수정
    path('delete/<int:class_id>/', views.delete, name='delete'),                   #클래스삭제
    path('search/', views.search, name='search'),                                  #필터링결과
    path('scrap/<int:class_id>/', views.scrap, name='scrap'),  
    path('participate/<int:class_id>/', views.participate, name='participate'),                     #스크랩
    path('recommend/<int:class_id>/', views.recommend, name='recommend'),          #추천
    path('review/<int:review_id>/', views.delete_review, name='deletereview'),                   #리뷰
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sclass/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views
import classregister.views
import storeregister.views
import cardnews.views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', classregister.views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('classregister/', include('classregister.urls')),
    path('storeregister/', include('storeregister.urls')),
    path('cardnews/', include('cardnews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storeregister/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'storeregister'


urlpatterns = [
    path('list/', views.store_list, name='list'),                   #가게리스트
    path('<int:store_id>', views.detail, name='detail'),                        #가게상세
    path('register/', views.register, name='register'),                         #가게등록 
    path('storeupdate/<int:store_id>', views.storeupdate, name='storeupate'),   #가게수정
    path('delete/<int:store_id>', views.delete, name='delete'),                 #가게삭제
    path('result/', views.result, name="result"),
]

classregister/models.py
from django.db import models
from django.conf import settings
from storeregister.models import Store

# Create your models here.
class Class(models.Model):

    CATEGORY = (
      ('요리', '요리'),
        ('수공예', '수공예'),
        ('꽃', '꽃'),
        ('미술', '미술'),
        ('음악', '음악'),
        ('미용', '미용'),
        ('운동', '운동'),
        ('커피/차', '커피/차'),
    )
    owner_name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    class_title = models.CharField(max_length=255)
    summary = models.CharField(max_length=255)
    describe = models.TextField()
    price = models.IntegerField()
    date = models.DateTimeField()
    category = models.CharField(max_length=10, choices=CATEGORY) # 미정
    current_number = models.IntegerField(default=0)
    max_number = models.IntegerField()
    img1 = models.ImageField(null=True,blank=True, upload_to='class/')
    img2 = models.ImageField(null=True,blank=True, upload_to='class/')
    img3 = models.ImageField(null=True,blank=True, upload_to='class/')
    img4 = models.ImageField(null=True,blank=True, upload_to='class/')
    img5 = models.ImageField(null=True,blank=True, upload_to='class/')

    #스크랩
    #users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Scrap')
  

    def __str__(self):
        return self.class_title

     
class Scrap(models.Model) :
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    my_class = models.ForeignKey(Class, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Book(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book_class = models.ForeignKey(Class, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review_class = models.ForeignKey(Class, on_delete=models.CASCADE)
    rate = models.IntegerField(default=5)
    content = models.TextField(max_length=500, blank=True)

classregister/forms.py
from django import forms
from .models import Class, Review

class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ('class_title', 'summary', 'describe', 'price', 
        'date', 'category', 'max_number', 
        'img1', 'img2', 'img3', 'img4', 'img5')

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('rate', 'content')

classregister/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib import messages
# 필요기능
import datetime
# 모델
from .models import Class, Book, Review, Scrap
from django.conf import settings
# 폼
from .forms import ClassForm, ReviewForm

# Create your views here.
def home(request):
    return render(request, 'classregister/home.html')

def class_list(request):
    classes = Class.objects.filter(date__gte=datetime.datetime.now()).order_by('-id')
    data = { 'classes' : classes }
    return render(request, 'classregister/class_list.html', data)

def detail(request, class_id):
    class_object = get_object_or_404(Class, pk=class_id)
    books = Book.objects.filter(book_class=class_id)
    books = [ i.user for i in books ]
    reviews = Review.objects.filter(review_class=class_id)
    data = { 'object' : class_object, 'reviews' : reviews, 'books':books }
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.review_class = class_object
            review.user = request.user
            review.save()
            return render(request, 'classregister/class_detail.html', data)
    else:
        form = ReviewForm()
        data['form'] = form
        return render(request, 'classregister/class_detail.html', data)

def register(request):
    if request.method == 'POST':
        form = ClassForm(request.POST)
        if form.is_valid():
            one_class = form.save(commit=False)
            one_class.owner_name = request.user
            one_class.save()
            return redirect('home')
    else:
        form = ClassForm()
        data = {'form' : form}
        return render(request, 'classregister/class_register.html', data)

def classupdate(request, class_id):
    one_class = get_object_or_404(Class, pk = class_id)
    if request.method == 'POST':
        form = ClassForm(request.POST, instance = one_class)
        if form.is_valid():
            one_class = form.save(commit=False)
            one_class.save()
            return redirect('classregister:detail', class_id = one_class.pk)
    else:
        form = ClassForm(instance=one_class)
        data = {'form':form}
        return render(request, 'classregister/class_edit.html', data)

def delete(request, class_id):
    one_class = get_object_or_404(Class, pk = class_id)
    if request.user != one_class.owner_name:
        return HttpResponse('글쓴이만 삭제 가능 합니다.')
    one_class.delete()
    return redirect('list')

def search(request):
    qs = Class.objects.all()
    q = request.GET.get('q','')
    if q:
        qs = qs.filter(class_title__icontains=q)

    data = { 
        'classes' : qs,
        'q' : q
         }
    return render(request, 'classregister/class_list.html', data)

def participate(request, class_id):
    user = get_object_or_404(get_user_model(), pk=request.user.id)
    one_class = get_object_or_404(Class, pk=class_id)
    booked = Book.objects.filter(user=user, book_class=one_class)
    if not booked:
        if one_class.book_set.count() >= one_class.max_number:
            messages.add_message(request, messages.INFO, '인원이 가득 찼습니다.')
            return redirect('classregister:detail', class_id = class_id)
        book = Book.objects.create(user=request.user, book_class=one_class)
        return redirect('classregister:detail', class_id = class_id)
    else:
        booked.delete()
        return redirect('classregister:detail', class_id = class_id)    


def scrap(request, class_id):
    user = get_object_or_404(get_user_model(), pk=request.user.id)
    one_class = get_object_or_404(Class, pk=class_id)
    scraped = Scrap.objects.filter(user=user, my_class=one_class)
    if not scraped:
        scrap = Scrap.objects.create(user=request.user, my_class=one_class)
        return redirect('classregister:detail', class_id = class_id)
    else:
        scraped.delete()
        return redirect('classregister:detail', class_id = class_id)

def recommend(request, class_id):
    return render(request, 'classregister/class_detail.html', data)

def delete_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    if request.user != review.user:
        return HttpResponse('해당 리뷰를 쓴 유저가 아닙니다')
    review.delete()
    return redirect('classregister:detail', class_id=review.review_class.id)

def review(request, class_id):
    return render(request, 'classregister/class_detail.html', data)

classregister/templates/classregister/class_detail.html
<!DOCTYPE html>
<html>
<head>
  <!-- Site made with Mobirise Website Builder v4.11.6, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets2/images/logo4.png" type="image/x-icon">
  <meta name="description" content="">

  <title></title>
  <link rel="stylesheet" href="assets2/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets2/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="assets2/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="assets2/theme/css/style.css">
  <link rel="preload" as="style" href="assets2/mobirise/css/mbr-additional.css"><link rel="stylesheet" href="assets2/mobirise/css/mbr-additional.css" type="text/css">



</head>
<body>
  {% extends 'base.html' %}
{% block content %}

  <section class="features16 cid-rIx8UK4a4u" id="features16-1a" data-sortbtn="btn-primary">

    {% if messages %}
    {% for msg in messages %}
    <div class="alert alert-warning" role="alert">
      {{msg}}
    </div>
    {% endfor %}
    {% endif %}

    <div class="container">
        <div class="row main align-items-center">
            <div class="col-md-6 image-element ">
              <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                {% if object.img1 %}
                <div class="carousel-item active">
                  <img src ="{{ object.img1.url }}" class="d-block w-100" >
                </div>
                {% endif %}
                {% if object.img2 %}
                <div class="carousel-item">
                  <img src ="{{ object.img2.url }}" class="d-block w-100">
                </div>
                {% endif %}
                {% if object.img3 %}
                <div class="carousel-item">
                  <img src ="{{ object.img3.url }}" class="d-block w-100">
                </div>
                {% endif %}
                {% if object.img2 %}
                <div class="carousel-item">
                  <img src ="{{ object.img4.url }}" class="d-block w-100">
                </div>
                {% endif %}
                {% if object.img3 %}
                <div class="carousel-item">
                  <img src ="{{ object.img5.url }}" class="d-block w-100">
                </div>
                {% endif %}
              </div>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">이전</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">다음</span>
              </a>
            </div>
            </div>


            <div class="col-md-6 text-element">
                <div class="text-content">
                    <h4 class="mbr-section-subtitle mbr-fonts-style mbr-black align-left display-5"><strong><br></strong><br><br><strong>{{object.category}}</strong></h4>
                    <h2 class="mbr-title pt-2 mbr-fonts-style align-left display-2">
                        {{object.class_title}}<br></h2>
                    <div class="mbr-section-text">
                        <p class="mbr-text pt-3 mbr-light mbr-fonts-style align-left display-7">강의자: {{object.owner_name}}님<br>가격: {{object.price}}원<br>시간: {{object.date|date:"Y년 m월 d일 H시 i분" }}<br>현재 신청 인원: {{object.book_set.count}}<br>최대 수용 인원: {{object.max_number}}</p>
                    </div>
                    <div class="mbr-section-btn pt-3 align-left">

                      {% if user == object.owner_name %}
                          <a href="{% url 'classregister:classupdate' object.id %}">수정</a>
                          <a href="{% url 'classregister:delete' object.id %}" onclick="return confirm('삭제하시겠습니까?')">삭제하기</a>

                      {% else %}

                      {% if object.book_set.count == 1 %}
                      <a class="btn btn-md btn-info display-4" href="{% url 'classregister:participate' object.id %}">신청 취소</a>
                      {% else %}
                      <a class="btn btn-md btn-info display-4" href="{% url 'classregister:participate' object.id %}">클래스신청</a>
                      {% endif %}

                      {% if object.scrap_set.count == 1 %}
                      <a class="btn btn-md btn-info display-4" href="{% url 'classregister:scrap' object.id %}">찜취소</a>
                      {% else %}
                      <a class="btn btn-md btn-info display-4" href="{% url 'classregister:scrap' object.id %}">찜하기</a>
                      {% endif %}

                      {% endif %}

                    </div>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section article content10 cid-rIx9PveWFN" id="content10-1f" data-sortbtn="btn-primary">



    <div class="container">
        <div class="media-container-row">
            <div class="col-md-10 col-lg-8">
                <p class="mbr-text m-0 mbr-fonts-style mbr-black display-7">{{object.describe}}</p>
            </div>
        </div>
    </div>
</section>

<section class="map1 cid-rIxafuMED3" id="map1-1g" data-sortbtn="btn-primary">



    <div class="google-map"><iframe frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAEIpgj38KyLFELm2bK9Y7krBkz1K-cMq8&amp;q=place_id:ChIJn6wOs6lZwokRLKy1iqRcoKw" allowfullscreen=""></iframe></div>
</section>

<section class="mbr-section content11 cid-rIxaWhtKWw" id="content11-1i" data-sortbtn="btn-primary">



    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-10">
                <div class="mbr-section-btn align-center">
                  {% if user in books %}
                  <a class="btn btn-primary display-4" href="{% url 'classregister:detail' object.id %}">리뷰쓰기</a>
                  <br>
                  <form method='POST'>
                      {% csrf_token %}
                      <table>
                          {{form.as_table}}
                      </table>
                      <br><br>
                      {% if form %}
                      <input type="submit" value="등록">
                      {% endif %}
                  </form>
                  {% endif %}

                  <br>
                  {% for review in reviews %}
                  {{ review.user.username }}
                  {{ review.content }}
                  <br>
                  {% if user == review.user %}
                  <a href="{% url 'classregister:deletereview' review.id %}" onclick="return confirm('삭제하시겠습니까?')">리뷰삭제</a>
                  {% endif %}
                  {% endfor %}
                  <br>
                  <a class="btn btn-primary display-4" href="{% url 'classregister:list' %}">클래스 리스트로</a>
                </div>
            </div>
        </div>
    </div>
</section>


  <script src="assets2/web/assets2/jquery/jquery.min.js"></script>
  <script src="assets2/popper/popper.min.js"></script>
  <script src="assets2/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets2/smoothscroll/smooth-scroll.js"></script>
  <script src="assets2/theme/js/script.js"></script>

{% endblock %}
</body>
</html>

classregister/templates/classregister/class_edit.html
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.11.6, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/logo4.png" type="image/x-icon">
  <meta name="description" content="">

  <title>class_register_edit</title>
  <link rel="stylesheet" href="assets/web/assets/mobirise-icons/mobirise-icons.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="assets/theme/css/style.css">
  <link rel="preload" as="style" href="assets/mobirise/css/mbr-additional.css"><link rel="stylesheet" href="assets/mobirise/css/mbr-additional.css" type="text/css">



</head>
<body>
  <section class="header9 cid-rIxcqchxtY mbr-parallax-background" id="header9-1n">



    <div class="mbr-overlay" style="opacity: 0.5; background-color: rgb(170, 171, 166);">
    </div>


    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8 align-center mbr-white">
                <h4 class="mbr-section-title mbr-fonts-style display-5"><br><br><br><br></h4>
                <h1 class="mbr-section-title mbr-bold mbr-fonts-style display-1">클래스 정보 수정<br></h1>


            </div>
        </div>
    </div>

</section>

<section class="form3 cid-rIxbETQZ36" id="form3-1l">




    <div class="container">
        <div class="row justify-content-center">
            <div class="form-1 col-md-10 col-lg-8">
                <h2 class="mbr-fonts-style mbr-fonts-style mbr-section-title align-center display-2"></h2>
                <h3 class="mbr-fonts-style mbr-fonts-style mbr-section-subtitle align-center display-5"></h3>
                <div class="form-wrap pt-4">
                <!---Formbuilder Form--->
                    <form method="POST" class="mbr-form form-with-styler">
                      <input type="hidden" name="email" value="1XSaVquCxtNGU+uX7/9YfoqGRcOI5YY9x9osQeic4iVZ0pXgG4Dqe47FAuykPuj4YrG9UliNl3KuuyuabgAHxw3tDWSlwZTO1wewVSh9Ctf0xk1YK/+dpeGvpqWbn0c=">
                        <div class="dragArea row">
                            <div data-for="name" class="col-lg-6  mb-3 form-group">
                                <input type="text" name="class_title" placeholder="강의명" class="form-control input display-7" required="required" id="name-form3-1l">
                            </div>
                            <div data-for="lastname" class="col-lg-6  mb-3 form-group">
                                <input type="text" name="summary" placeholder="한줄로 요약한 내 강의" class="form-control input display-7" id="message-form3-1l">
                            </div>

                            <div data-for="name" class="col-lg-6  mb-3 form-group">
                                <input type="text" name="price" placeholder="가격" class="form-control input display-7" required="required" id="name-form3-1l">
                            </div>

                            <div data-for="name" class="col-lg-6  mb-3 form-group">
                                <input type="text" name="date" placeholder="날짜" class="form-control input display-7" required="required" id="name-form3-1l">
                            </div>

                            <div data-for="name" class="col-lg-6  mb-3 form-group">
                                <input type="text" name="category" placeholder="분류" class="form-control input display-7" required="required" id="name-form3-1l">
                            </div>

                            <div data-for="name" class="col-lg-6  mb-3 form-group">
                                <input type="text" name="max_number" placeholder="최대 수용 인원" class="form-control input display-7" required="required" id="name-form3-1l">
                            </div>

                            <div data-for="name" class="col-lg-6  mb-3 form-group">
                                <input type="text" name="describe" placeholder="세부설명" class="form-control input display-7" required="required" id="name-form3-1l">
                            </div>
                              <h4 class="mbr-section-subtitle mbr-fonts-style mbr-black align-left display-5">클래스를 설명해 줄 이미지 파일을 넣어주세요.</h4>
                              <input type="file" class="form-control-file" id="exampleFormControlFile1" name="img1">
                              <input type="file" class="form-control-file" id="exampleFormControlFile1" name="img2">
                              <input type="file" class="form-control-file" id="exampleFormControlFile1" name="img3">
                              <input type="file" class="form-control-file" id="exampleFormControlFile1" name="img4">
                              <input type="file" class="form-control-file" id="exampleFormControlFile1" name="img5">
                            <div class="col-md-12 input-group-btn  mt-2 align-left"><button type="submit" class="btn btn-form btn-bgr btn-primary display-4">수정하기</button></div>
                        </div>
                    </form><!---Formbuilder Form--->
                </div>
            </div>
        </div>
   </div>
</section>


  <script src="assets/web/assets/jquery/jquery.min.js"></script>
  <script src="assets/popper/popper.min.js"></script>
  <script src="assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="assets/smoothscroll/smooth-scroll.js"></script>
  <script src="assets/mbr-animated-bg-text/mbr-animated-bg-text.js"></script>
  <script src="assets/parallax/jarallax.min.js"></script>
  <script src="assets/theme/js/script.js"></script>
  <script src="assets/formoid/formoid.min.js"></script>


</body>
</html>

classregister/templates/classregister/home.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}

<!DOCTYPE html>
<html  >
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets2/images/logo-mobile-164x174.png' %}" type="image/x-icon">
  <meta name="description" content="">
  
  <title>Home</title>
  <link rel="stylesheet" href="{% static 'assets2/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/socicon/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'assets2/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets2/mobirise/css/mbr-additional.css' %}" type="text/css">
  
  
  
</head>
<body>
  

<section class="header9 cid-rIsBNxCYox mbr-fullscreen mbr-parallax-background" id="header9-q" data-sortbtn="btn-primary">

    

    <div class="mbr-overlay" style="opacity: 0.5; background-color: rgb(170, 171, 166);">
    </div>

    
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8 align-center mbr-white">
                <h4 class="mbr-section-title mbr-fonts-style display-5"><strong>주변 시장의 숨겨진 이야기</strong></h4>
                <h1 class="mbr-section-title mbr-bold mbr-fonts-style display-1">
                    SClass</h1>
                <p class="mbr-text pb-3 mbr-fonts-style display-7"><strong>
                    시장 상인들과 함께하는 특별한 클래스를 체험해보세요.
                </strong></p>
                <div class="mbr-section-btn"><a href="{% url 'classregister:list' %}"class="btn btn-lg btn-primary display-4" type="submit">개설 클래스 보기</a> <a href="{% url 'storeregister:list' %}" class="btn btn-lg btn-primary display-4" type="submit">시장 상점 보기</a></div>
            </div>
        </div>
    </div>
    
</section>

<section class="features4 cid-rIsGpv9Ofn" id="features4-v" data-sortbtn="btn-primary">

    

    
    <div class="container">
        <div class="row main">
            <div class="col-md-6 image-element">
                <div class="mbr-figure"><iframe class="mbr-embedded-video" src="https://www.youtube.com/embed/jYXgTpjIGg0?rel=0&amp;amp;showinfo=0&amp;autoplay=0&amp;loop=0" width="1280" height="720" frameborder="0" allowfullscreen></iframe></div>
            </div>
            <div class="col-md-6 text-element">
                <div class="text-content">
                    <h4 class="mbr-section-subtitle mbr-fonts-style mbr-white align-left display-5"><strong>SClass 란?</strong></h4><strong>
                    <h2 class="mbr-title pt-2 mbr-fonts-style align-left mbr-white display-2">시장 상인들의 클래스 제공 플랫폼입니다</h2>
                    <p class="mbr-text pt-3 mbr-light mbr-fonts-style align-left mbr-white display-7">클래스 등록과 관리. Sclass를 통해 간편하게 해보세요.<br>Sclass는 상인들의 <b>숨겨진 이야기</b>를 발굴합니다. Sclass를 통해 시장 주변 사람들은 집 근처 상인분들의 기술을 배우고, 숨겨져있던 이야기를 듣고 소통하며 그 주변의 다른 상권까지도 관심을 가지게 될 것입니다. 시장에 다시 생생한 활기를 불어넣도록 말이죠.&nbsp;<br></p>
                    
                </strong></div><strong>
            </strong></div><strong>
        </strong></div><strong>
    </strong></div><strong>          
</strong></section>

<section class="cid-rIxlDnxhnm" id="footer2-1v" data-sortbtn="btn-primary">

    

    

    <div class="container">
        <div class="row align-center justify-content-center align-items-center">
            <div class="logo-section col-sm-12 col-lg-4">
                <a href="#"><img src="{% static 'assets2/images/logo-web-164x48.png' %}" height="128" alt="Mobirise" title="" style="height: 3.8rem;">
                </a>
            </div>
            <div class="col-sm-12 col-lg-4 mbr-text mbr-fonts-style mbr-light display-7">
                SClass
            <div>Phone: +82 10-1234-1234</div><div>Email: olo5112olo@naver.com</div></div>
            
        </div>
    </div>
</section>


  <script src="{% static 'assets2/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets2/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets2/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets2/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets2/touchswipe/jquery.touch-swipe.min.js' %}"></script>
  <script src="{% static 'assets2/mbr-animated-bg-text/mbr-animated-bg-text.js' %}"></script>
  <script src="{% static 'assets2/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'assets2/dropdown/js/nav-dropdown.js' %}"></script>
  <script src="{% static 'assets2/dropdown/js/navbar-dropdown.js' %}"></script>
  <script src="{% static 'assets2/theme/js/script.js' %}"></script>
  
  
</body>
</html>
{% endblock %}