accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('profile_show/', views.profile_show, name='profile_show'),
    path('signup_complete/', views.signup_complete, name="signup_complete"),
    path('mypage/', views.mypage, name='mypage'),
    path('my_scrap/', views.my_scrap, name='my_scrap'),
    path('my_review/', views.my_review, name='my_review'),
    path('my_recommend/', views.my_recommend, name='my_recommend'),
    path('my_consult/', views.my_consult, name='my_consult'),
    path('my_store/', views.my_store, name='my_store'),
    path('my_class/', views.my_class, name='my_class'),
    path('my_student/<int:class_id>', views.my_student, name='my_student'),
    path('my_enroll/', views.my_enroll, name='my_enroll'),
]

classregister/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'classregister'

urlpatterns = [
    path('list/', views.class_list, name='list'),                                  #클래스리스트
    path('<int:class_id>/', views.detail, name='detail'),                          #클래스상세
    path('register/', views.register, name='register'),                            #클래스등록
    path('classupdate/<int:class_id>/', views.classupdate, name='classupdate'),    #클래스수정
    path('delete/<int:class_id>/', views.delete, name='delete'),                   #클래스삭제
    path('search/', views.search, name='search'),                                  #필터링결과
    path('scrap/<int:class_id>/', views.scrap, name='scrap'),  
    path('participate/<int:class_id>/', views.participate, name='participate'),                     #스크랩
    path('recommend/<int:class_id>/', views.recommend, name='recommend'),          #추천
    path('review/<int:review_id>/', views.delete_review, name='deletereview'),                   #리뷰
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sclass/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views
import classregister.views
import storeregister.views
import cardnews.views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', classregister.views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('classregister/', include('classregister.urls')),
    path('storeregister/', include('storeregister.urls')),
    path('cardnews/', include('cardnews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storeregister/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'storeregister'


urlpatterns = [
    path('list/', views.store_list, name='list'),                   #가게리스트
    path('<int:store_id>', views.detail, name='detail'),                        #가게상세
    path('register/', views.register, name='register'),                         #가게등록 
    path('storeupdate/<int:store_id>', views.storeupdate, name='storeupate'),   #가게수정
    path('delete/<int:store_id>', views.delete, name='delete'),                 #가게삭제
    path('result/', views.result, name="result"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from classregister.models import Class
from storeregister.models import Store
from django.core.validators import RegexValidator
from django.conf import settings


# Create your models here.
class User(AbstractUser):
   seller = models.BooleanField(default=False)
   phone = models.CharField(
        null=True,
        blank=True,
        max_length=13,
        unique=True,
        validators=[
            RegexValidator(
                regex=r"\d{3}-\d{3,4}-\d{4}",
                message='010-1234-5678 형식으로 입력하세요.',
            )
        ]
    )

    

accounts/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'seller', 'phone')
        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'class': "form-control input display-7",
                    'required': "required",
                    'id': "name-form3-2w",
                    'placeholder': '이름',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': "form-control input display-7",
                    'required': "required",
                    'id': "name-form3-2w",
                    'placeholder': '성',
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'type': 'email',
                    'class': "form-control input display-7",
                    'required': "required",
                    'id': "name-form3-2w",
                    'placeholder': '이메일',
                }
            ),
            'phone': forms.TextInput(
                attrs={
                    'class': "form-control input display-7",
                    'required': "required",
                    'id': "name-form3-2w",
                    'placeholder': '전화번호',
                }
            ),
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth
from .models import User
from classregister.models import Class, Scrap, Review, Book
from storeregister.models import Store, Recommend
from .forms import UserForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import transaction
# Create your views here.

def signup(request):
    #signup 버튼을 눌렀을 때 일어나야 하는 일
    if request.method == 'POST': #form으로 넘긴 값이 POST 이면
        if request.POST['password1'] == request.POST['password2']:  #비밀번호 두 개가 서로 일치하면
            try:
                user = User.objects.get(username=request.POST['username']) #POST 형식으로 가져온 username 과 일치하는 User 객체의 username을 가져와서 user 변수에 저장
                return render(request, 'accounts/signup.html', {'error':'이미 존재하는 아이디입니다'})
            except User.DoesNotExist:    #username과 일치하는 값을 가진 객체가 없어서 try 를 실행하지 못한 경우
                user = User.objects.create_user(    #User객체 새로 생성 POST로 가져온 username과 password1 필드에 저장
                    request.POST['username'], password=request.POST['password1'])
                auth.login(request, user)         #로그인 실행
                return redirect('profile_edit')
        else:
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 일치하지 않습니다'})
    else: 
        return render(request, 'accounts/signup.html') 


def login(request):
    if request.method == 'POST':    #로그인 버튼을 눌렀을때 
        username = request.POST['username']    #username 저장
        password = request.POST['password']    #password 저장
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:    #사용자가 정보를 알맞게 입력한 경우
            auth.login(request, user)   #로그인 실행
            return redirect('home')     #홈으로 이동
        else:
            return render(request, 'accounts/login.html', {'error': '아이디나 비밀번호가 일치하지 않습니다'})
    else: 
        return render(request, 'accounts/login.html')

def signup_complete(request):
    return render(request, 'accounts/signup_complete.html') 

@login_required   
def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('home')
    return render(request, 'accounts/signup.html')

@login_required
def mypage(request):
        user = User.objects.get(username=request.user)
        return render(request, 'accounts/mypage.html', {'user':user})

@login_required
def my_class(request):
    classes = Class.objects.filter(owner_name=request.user)
    return render(request, 'accounts/my_class.html', {'classes' : classes})

def my_consult(request):
    return render(request, 'accounts/my_consult.html')

@login_required
def my_recommend(request):
    recommends = Recommend.objects.filter(user=request.user)
    return render(request, 'accounts/my_recommend.html', {'recommends': recommends})

@login_required
def my_review(request):
    reviews = Review.objects.filter(user=request.user)
    return render(request, 'accounts/my_review.html', {'reviews': reviews})

@login_required    
def my_scrap(request):
    scraps = Scrap.objects.filter(user=request.user)
    return render(request, 'accounts/my_scrap.html', {'scraps':scraps})

@login_required
def my_store(request):
    stores = Store.objects.filter(user = request.user)
    return render(request, 'accounts/my_store.html', {'stores':stores}) 

@login_required
def my_student(request, class_id):
    myclass = get_object_or_404(Class, pk = class_id)
    books = Book.objects.filter(book_class=myclass)
    current_number = myclass.book_set.count()
    return render(request, 'accounts/my_student.html', {'class':myclass, 'books':books, 'current_number':current_number}) 

@login_required
def my_enroll(request):
    books = Book.objects.filter(user=request.user)
    return render(request, 'accounts/my_enroll.html', {'books': books}) 

@login_required
@transaction.atomic
def profile_edit(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, ('Your profile was successfully updated!'))
            return redirect('profile_show')
        else:
            messages.error(request, ('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        return render(request, 'accounts/profile_edit.html', {'user_form':user_form})
    return render(request, 'accounts/profile_edit.html') 

@login_required
def profile_show(request):
    return render(request, 'accounts/profile_show.html') 

###데코레이션
#로그인, 사인업 안돼있으면 

accounts/templates/accounts/my_enroll.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.11.6, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets/images/logo4.png' type="image/x-icon" %}">
  <meta name="description" content="">
  
  <title>my_enroll</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
  
  
  
</head>
<body>
  <section class="features14 popup-btn-cards cid-rIsITcURvh mbr-parallax-background" id="features14-1j">

    

    
    <a class="full-link" href=""></a>
    <div class="container-fluid card-wrapper">
        <div class="row justify-content-center align-items-center" style="min-height: 12vw;">
             <div class="col-xl-10 col-lg-10 col-md-12 text-block">
                <h2 class="mbr-section-title mbr-fonts-style mbr-light mbr-white mbr-bold display-2">MY CLASS<br> REGISTRATION</h2>                 
             </div>
        </div>
    </div>
</section>

<section class="accordion1 cid-rIsITedUZz" id="accordion1-1k">

    

    
    <div class="container">
        <h2 class="mbr-fonts-style mbr-section-title align-center display-2">수강신청한 클래스</h2>
        <h3 class="mbr-fonts-style mbr-section-subtitle align-center display-5">My Class Registration</h3>
        <div class="row justify-content-center pt-4">
            <div class="col-md-10 col-lg-8 content-block">
            <div class="accordion-content">
                <div id="bootstrap-accordion_19" class="panel-group accordionStyles accordion " role="tablist" aria-multiselectable="true">
                    {% for book in books.all %}    
                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                <a href="{% url 'classregister:detail' book.book_class.id %}">
                                    <h4 class="mbr-fonts-style header-text display-5">{{book.book_class.class_title}}</h4>
                                </a>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
            </div>
    </div>
    </div>         
</section>


  <script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets/mbr-popup-btns/mbr-popup-btns.js' %}"></script>
  <script src="{% static 'assets/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'assets/mbr-switch-arrow/mbr-switch-arrow.js' %}"></script>
  <script src="{% static 'assets/theme/js/script.js' %}"></script>
  
</body>
</html>
{% endblock %}

accounts/templates/accounts/my_review.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.11.6, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets/images/logo4.png' %}" type="image/x-icon">
  <meta name="description" content="">
  
  <title>my_review</title>
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/datatables/data-tables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
  
  
  
</head>
<body>
  <section class="features14 popup-btn-cards cid-rIsIZ5DjMM mbr-parallax-background" id="features14-1r">

    

    <div class="mbr-overlay" style="opacity: 0.4; background-color: rgb(0, 0, 0);">
    </div>
    <a class="full-link" href=""></a>
    <div class="container-fluid card-wrapper">
        <div class="row justify-content-center align-items-center" style="min-height: 12vw;">
             <div class="col-xl-10 col-lg-10 col-md-12 text-block">
                <h2 class="mbr-section-title mbr-fonts-style mbr-light mbr-white mbr-bold display-2">REVIEW</h2>                 
             </div>
        </div>
    </div>
</section>

<section class="table1 section-table cid-rItu6KLzJh" id="table1-2y">

    

    
    <div class="container">
        <div class="media-container-row align-center">
            <div class="col-12 col-md-12">
                <h2 class="mbr-section-title mbr-fonts-style mbr-black display-2">
                    나의 리뷰</h2>
                <h3 class="mbr-section-subtitle mbr-fonts-style pb-4 display-5">My Review</h3>
                <div class="table-wrapper">
                    <div class="container">
                        
                    </div>
                    <div class="container-fluid scroll">
                        <table class="table" cellspacing="0">

                            <tbody>


                                {% for review in reviews.all %}

                                <tr> 
                                    <a href="{% url 'classregister:detail' review.review_class.id %}">    
                                        <td class="body-item mbr-fonts-style display-7">{{review.review_class.class_title}}</td><td class="body-item mbr-fonts-style display-7">{{review.rate}}</td></a>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="container-fluid table-info-container">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


  <script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets/mbr-popup-btns/mbr-popup-btns.js' %}"></script>
  <script src="{% static 'assets/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'assets/datatables/jquery.data-tables.min.js' %}"></script>
  <script src="{% static 'assets/datatables/data-tables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'assets/theme/js/script.js' %}"></script>
  
  
</body>
</html>
{% endblock %}

accounts/templates/accounts/my_scrap.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.11.6, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets/images/logo4.png' %}" type="image/x-icon">
  <meta name="description" content="">
  
  <title>my_scrap</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css' %}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
  
  
  
</head>
<body>    
  <section class="features14 popup-btn-cards cid-rIvXeI4E36 mbr-parallax-background" id="features14-38">

    

    
    <a class="full-link" href=""></a>
    <div class="container-fluid card-wrapper">
        <div class="row justify-content-center align-items-center" style="min-height: 12vw;">
             <div class="col-xl-10 col-lg-10 col-md-12 text-block">
                <h2 class="mbr-section-title mbr-fonts-style mbr-light mbr-white mbr-bold display-2">MY SCRAP</h2>                 
             </div>
        </div>
    </div>
</section>

<section class="accordion1 cid-rIvXeJakw2" id="accordion1-39">

    

    
    <div class="container">
        <h2 class="mbr-fonts-style mbr-section-title align-center display-2">스크랩한 클래스</h2>
        <h3 class="mbr-fonts-style mbr-section-subtitle align-center display-5">My Scrap</h3>
        <div class="row justify-content-center pt-4">
            <div class="col-md-10 col-lg-8 content-block">
            <div class="accordion-content">
                <div id="bootstrap-accordion_35" class="panel-group accordionStyles accordion " role="tablist" aria-multiselectable="true">
                    {% for scrap in scraps.all %}    
                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                    <a href="{% url 'classregister:detail' scrap.my_class.id %}">
                                    <h4 class="mbr-fonts-style header-text display-5">{{scrap.my_class.class_title}}</h4>

                                </a>
                            </div>
                        </div>
                    {% endfor %}
               
                </div>
            </div>
            </div>
    </div>
    </div>         
</section>


  <script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets/mbr-popup-btns/mbr-popup-btns.js' %}"></script>
  <script src="{% static 'assets/parallax/jarallax.min.js' %}"></script>
  <script src="{% static 'assets/mbr-switch-arrow/mbr-switch-arrow.js' %}"></script>
  <script src="{% static 'assets/theme/js/script.js' %}"></script>
  
</body>
</html>
{% endblock %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
{% if user.is_authenticated %}
<!DOCTYPE html>
<html  >
<head>
  <!-- Site made with Mobirise Website Builder v4.11.6, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.11.6, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'assets/images/logo4.png'%}" type="image/x-icon">
  <meta name="description" content="">
  
  <title>mypage</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css'%}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css'%}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css'%}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css'%}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css'%}">
  <link rel="preload" as="style" href="{% static 'assets/mobirise/css/mbr-additional.css'%}"><link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css'%}" type="text/css">
  
  
  
</head>
<body>

        
  <section class="features14 popup-btn-cards cid-rIsEFpFcr4 mbr-parallax-background" id="features14-19">

    

    
    <a class="full-link" href=""></a>
    <div class="container-fluid card-wrapper">
        <div class="row justify-content-center align-items-center" style="min-height: 12vw;">
             <div class="col-xl-10 col-lg-10 col-md-12 text-block">
                <h2 class="mbr-section-title mbr-fonts-style mbr-light mbr-white mbr-bold display-2">MY PAGE</h2>                 
             </div>
        </div>
    </div>
</section>

<section class="accordion1 cid-rIsETYg5HB" id="accordion1-1g">

    

    
    <div class="container">
        <h2 class="mbr-fonts-style mbr-section-title align-center display-2">나의 회원정보</h2>
        <h3 class="mbr-fonts-style mbr-section-subtitle align-center display-5">my page</h3>
        <div class="row justify-content-center pt-4">
            <div class="col-md-10 col-lg-8 content-block">
            <div class="accordion-content">
                <div id="bootstrap-accordion_16" class="panel-group accordionStyles accordion " role="tablist" aria-multiselectable="true">
                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                <a href="{% url 'profile_show' %}">
                                    <h4 class="mbr-fonts-style header-text display-5">내 프로필</h4>

                                </a>
                            </div>

                        </div>
                
                        <div class="card">
                            <div class="card-header" role="tab" id="headingTwo">
                                <a href="{% url 'my_enroll' %}">
                                    <h4 class="mbr-fonts-style header-text display-5">수강신청한 클래스</h4>
                                </a>
                                
                            </div>

                        </div>
                
                        <div class="card">
                            <div class="card-header" role="tab" id="headingThree">
                                <a href="{% url 'my_scrap' %}">
                                    <h4 class="mbr-fonts-style header-text display-5">스크랩한 클래스</h4>

                                </a>
                            </div>

                        </div>
                
                        <div class="card">
                            <div class="card-header" role="tab" id="headingFour">
                                <a href="{% url 'my_review' %}">
                                    <h4 class="mbr-fonts-style header-text display-5">나의 리뷰</h4>

                                </a>
                            </div>

                        </div>

                        
                </div>
            </div>
            </div>
    </div>
    </div>         
</section>



{% if user.seller is True %}
<section class="accordion1 cid-rIsHAsPqv7" id="accordion1-1h">

    

    
    <div class="container">
        <h2 class="mbr-fonts-style mbr-section-title align-center display-2">내 클래스 관리하기</h2>
        <h3 class="mbr-fonts-style mbr-section-subtitle align-center display-5">My Class</h3>
        <div class="row justify-content-center pt-4">
            <div class="col-md-10 col-lg-8 content-block">
            <div class="accordion-content">
                <div id="bootstrap-accordion_17" class="panel-group accordionStyles accordion " role="tablist" aria-multiselectable="true">
                        <div class="card">
                            <div class="card-header" role="tab" id="headingOne">
                                <a href="{% url 'my_store' %}">
                                    <h4 class="mbr-fonts-style header-text display-5">내 가게 보러가기</h4>

                                </a>
                            </div>

                        </div>
                
                        <div class="card">
                            <div class="card-header" role="tab" id="headingTwo">
                                <a href="{% url 'my_class' %}">
                                    <h4 class="mbr-fonts-style header-text display-5">내가 개설한 클래스</h4>
                                </a>
                                
                            </div>

                        </div>
                
                        <div class="card">
                            <div class="card-header" role="tab" id="headingThree">
                                <a href="{% url 'classregister:register' %}">
                                    <h4 class="mbr-fonts-style header-text display-5">클래스 등록하기</h4>

                                </a>
                            </div>

                        </div>
                
                        <div class="card">
                            <div class="card-header" role="tab" id="headingFour">
                                    <a href="{% url 'storeregister:register' %}">
                                    <h4 class="mbr-fonts-style header-text display-5">가게 등록하기</h4>

                                </a>
                            </div>

                        </div>
                
                        
                
                        
                </div>
            </div>
            </div>
    </div>
    </div>         
</section>
{% endif %}



  <script src="{% static 'assets/web/assets/jquery/jquery.min.js'%}"></script>
  <script src="{% static 'assets/popper/popper.min.js'%}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'assets/smoothscroll/smooth-scroll.js'%}"></script>
  <script src="{% static 'assets/mbr-popup-btns/mbr-popup-btns.js'%}"></script>
  <script src="{% static 'assets/parallax/jarallax.min.js'%}"></script>
  <script src="{% static 'assets/mbr-switch-arrow/mbr-switch-arrow.js'%}"></script>
  <script src="{% static 'assets/theme/js/script.js'%}"></script>
  
{% endif %}



{% endblock %}  
</body>
</html>