sclass/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views
import classregister.views
import storeregister.views
import cardnews.views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', classregister.views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('classregister/', include('classregister.urls')),
    path('storeregister/', include('storeregister.urls')),
    path('cardnews/', include('cardnews.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

storeregister/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'storeregister'


urlpatterns = [
    path('list/', views.store_list, name='list'),                   #가게리스트
    path('<int:store_id>', views.detail, name='detail'),                        #가게상세
    path('register/', views.register, name='register'),                         #가게등록 
    path('storeupdate/<int:store_id>', views.storeupdate, name='storeupate'),   #가게수정
    path('delete/<int:store_id>', views.delete, name='delete'),                 #가게삭제
    path('result/', views.result, name="result"),
]

storeregister/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Store(models.Model):
    REGION_CHOICES = (
      ('GN', '강남구'),
      ('SC', '서초구'),
      ('YS', '용산구'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    store_title = models.CharField(max_length=100)
    region = models.CharField(max_length=100, choices=REGION_CHOICES)
    address = models.TextField(max_length=200)
    detailaddr = models.TextField(max_length=200)
    homepage = models.URLField(max_length=200)
    photo = models.ImageField(null=True,blank=True, upload_to='store/')
    describe = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
      return self.store_title

class Recommend(models.Model) :
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)    

storeregister/forms.py
from django import forms
from .models import Store

class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ['store_title', 'region', 'address', 'detailaddr', 
                'homepage', 'describe', 'photo']

        widgets={
            'store_title' : forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'제목을 입력하세요',
                }
            ),

            'region' : forms.Select(
                attrs={
                    'class':'form-control',
                }
            ),

            'homepage': forms.TextInput(
                attrs={
                    'class':'form-control',
                }                
            ),

            'describe' : forms.Textarea(
                attrs={
                    'class':'form-control',
                }                
            ),
        }

        labels = {
            'store_title' : '스토어 이름', 
            'region' : '지역',  
            'homepage' : '홈페이지',
            'describe' : '설명', 
            'photo' : '사진',
        }

storeregister/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Store
from .forms import StoreForm
from accounts.models import User

# Create your views here.

##리스트 보여주기 (list)
def store_list(request):
    stores = Store.objects               
    return render(request, 'storeregister/store_list.html', {'stores' : stores})


##상세페이지 (R)
def detail(request, store_id):
    store = get_object_or_404(Store, pk=store_id)
    return render(request, 'storeregister/store_detail.html', {'store':store})


##스토어 등록 (C)
@login_required
def register(request):
    if request.method == 'POST':
        form = StoreForm(request.POST, request.FILES)
        if form.is_valid():
            store = form.save(commit=False)
            store.user = request.user  ##username 자동 설정
            store.save()
            return redirect('storeregister:list')
    else : 
        form=StoreForm()
        return render(request, 'storeregister/store_register.html', {'form':form})


##스토어 수정(U)
@login_required
def storeupdate(request, store_id):
    store = get_object_or_404(Store, pk=store_id)
    if request.method=='POST':
        form = StoreForm(request.POST, instance=store)
        if form.is_valid():
            store = form.save(commit=False)
            store.user = request.user  ##username 자동 설정
            store.save()
            return redirect('storeregister:detail', store_id=store.pk)    
    else:
        if store.user == User.objects.get(username=request.user.get_username()) :  ##자신의 글일때만 수정 가능
            form = StoreForm(instance=store)
            return render(request, 'storeregister/store_edit.html', {'form':form})

        else :
            return redirect('storeregister:detail', store_id=store.pk)    ##자신의 글 아니면 해당글 detail로 redirect


##스토어 삭제(D)
@login_required
def delete(request, store_id):
    store = get_object_or_404(Store, pk=store_id)
    if store.user == User.objects.get(username=request.user.get_username()) : ##자신의 글일때만 삭제 가능
        store.delete()
        return redirect('storeregister:list')
    else:
        return redirect('storeregister:detail', store_id=store.pk)   ##자신의 글 아니면 해당글 detail로 redirect



#필터링
def result(request) : 
    store_object = Store.objects
    query = request.GET.get('query','')
    if query:
        store_object = store_object.filter(region=query)
        return render(request,'storeregister/store_result.html',{'result':store_object} )

storeregister/templates/storeregister/store_detail.html
<p>가게상세페이지</p>
{% extends 'base.html' %}
{% block content %}

    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8">
        </head>
        <body>

            {{ store.user }} <br>
            {{ store.store_title }} <br>
            {{ store.date }} <br>
            {{ store.region }} <br>
            {{ store.address }} <br>
            {{ store.detailaddr }} <br>
            {{ store.homepage }} <br>
            {{ store.describe }} <br>
            {% if store.photo %}
            <img src ="{{ store.photo.url }}" width=200> <br>
            {% endif %}


            <!--다음지도api - 배포시 다음에서 플랫폼 도메인 주소 바꾸기!-->
            <!--https://developers.kakao.com/apps/367921/settings/general-->
                    
            <div id="map" style="width:350px;height:350px;"></div>

            <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=88fef5eac83ce4f2e8d43c348fcb0e0b&libraries=services"></script>
            <script>
            var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
                mapOption = {
                    center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
                    level: 3 // 지도의 확대 레벨
                };  

            // 지도를 생성합니다    
            var map = new kakao.maps.Map(mapContainer, mapOption); 

            // 주소-좌표 변환 객체를 생성합니다
            var geocoder = new kakao.maps.services.Geocoder();

            // 주소로 좌표를 검색합니다
            geocoder.addressSearch('{{ store.address }}', function(result, status) {

                // 정상적으로 검색이 완료됐으면 
                if (status === kakao.maps.services.Status.OK) {

                    var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                    // 결과값으로 받은 위치를 마커로 표시합니다
                    var marker = new kakao.maps.Marker({
                        map: map,
                        position: coords
                    });

                    // 인포윈도우로 장소에 대한 설명을 표시합니다
                    var infowindow = new kakao.maps.InfoWindow({
                        content: '<div style="width:150px;text-align:center;padding:6px 0;">{{ store.store_title }}</div>'
                    });
                    infowindow.open(map, marker);

                    // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                    map.setCenter(coords);
                } 
            });    
            </script>

            {% if request.user == store.user %}
                <br>
                <a href="{% url 'storeregister:storeupate' store.id %}">수정하기</a><br>
                <a href="{% url 'storeregister:delete' store.id %}">삭제하기</a>
                <br><br>
            {% endif %}


            <a href="{% url 'storeregister:list' %}">글 목록</a>

        </body>
    </html>

{% endblock %}

storeregister/templates/storeregister/store_edit.html
<p>가게정보수정페이지</p>
{% extends 'base.html' %}
{% block content %}
    <form method='POST'>
        {% csrf_token %}
        {{ form.store_title.label }} {{ form.store_title }} <br>
        {{ form.region.label }} {{ form.region }}<br>
        {{ form.homepage.label }} {{ form.homepage }}<br>
        {{ form.describe.label }} {{ form.describe }}<br>
        {{ form.photo.label }} {{ form.photo }}<br>
            
            
            <!--다음 api-->
            <!--수정 시 address, detailaddr는 다시 쳐야함-->
            <input type="text"  id="sample6_postcode" placeholder="우편번호">
            <input type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기"><br>
            <input type="text" name="address" id="sample6_address" placeholder="주소"><br>  <!--address-->
            <input type="text" name="detailaddr" id="sample6_detailAddress" placeholder="상세주소"> <!--detailaddr-->
            <input type="text" id="sample6_extraAddress" placeholder="참고항목">
    
            <script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
            <script>
                function sample6_execDaumPostcode() {
                    new daum.Postcode({
                        oncomplete: function(data) {
                            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.
    
                            // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                            var addr = ''; // 주소 변수
                            var extraAddr = ''; // 참고항목 변수
    
                            //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                            if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                                addr = data.roadAddress;
                            } else { // 사용자가 지번 주소를 선택했을 경우(J)
                                addr = data.jibunAddress;
                            }
    
                            // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                            if(data.userSelectedType === 'R'){
                                // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                                // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                                    extraAddr += data.bname;
                                }
                                // 건물명이 있고, 공동주택일 경우 추가한다.
                                
                                if(data.buildingName !== '' && data.apartment === 'Y'){
                                    extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                                }
                                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                                if(extraAddr !== ''){
                                    extraAddr = ' (' + extraAddr + ')';
                                }
                                // 조합된 참고항목을 해당 필드에 넣는다.
                                document.getElementById("sample6_extraAddress").value = extraAddr;
                            
                            } else {
                                document.getElementById("sample6_extraAddress").value = '';
                            }
    
                            // 우편번호와 주소 정보를 해당 필드에 넣는다.
                            document.getElementById('sample6_postcode').value = data.zonecode;
                            document.getElementById("sample6_address").value = addr;
                            // 커서를 상세주소 필드로 이동한다.
                            document.getElementById("sample6_detailAddress").focus();
                        }
                    }).open();
                }
            </script>
            
            <br>
            <input type="submit" value="등록">
    </form>
{% endblock %}

storeregister/templates/storeregister/store_list.html
{% extends 'base.html' %}
{% block content %}

    <p>가게리스트</p>

    <!--필터링-->
    <form action="{% url 'storeregister:result' %}" method="get">
        <select name='query'>
            <option value="{{None}}">지역</option>
            <option value="GN">강남</option>
            <option value="SC">서초</option>
            <option value="YS">용산</option>
        </select>
        <input type="submit" name="" value="검색">
    </form>
    

    <!--글목록-->
    {% for store in stores.all %}
        <a href="{% url 'storeregister:detail' store.id %}">{{ store.store_title }}</a>
        {{ store.region }}
        <br>
    {% endfor %}

    <br>
    <a href="{% url 'storeregister:register' %}">스토어 등록하기</a>

{% endblock %}

storeregister/templates/storeregister/store_register.html
<p>가게등록페이지</p>
{% extends 'base.html' %}
{% block content %}
    <form method='POST' enctype="multipart/form-data" novalidate>

        {% csrf_token %}
        {{ form.store_title.label }} {{ form.store_title }} <br>
        {{ form.region.label }} {{ form.region }}<br>
        {{ form.homepage.label }} {{ form.homepage }}<br>
        {{ form.describe.label }} {{ form.describe }}<br>
        {{ form.photo.label }} {{ form.photo }}<br>
        
        
        <!--다음 api-->
        <input type="text"  id="sample6_postcode" placeholder="우편번호">
        <input type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기"><br>
        <input type="text" name="address" id="sample6_address" placeholder="주소"><br>  <!--address-->
        <input type="text" name="detailaddr" id="sample6_detailAddress" placeholder="상세주소"> <!--detailaddr-->
        <input type="text" id="sample6_extraAddress" placeholder="참고항목">

        <script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
        <script>
            function sample6_execDaumPostcode() {
                new daum.Postcode({
                    oncomplete: function(data) {
                        // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                        // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                        // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                        var addr = ''; // 주소 변수
                        var extraAddr = ''; // 참고항목 변수

                        //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                        if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                            addr = data.roadAddress;
                        } else { // 사용자가 지번 주소를 선택했을 경우(J)
                            addr = data.jibunAddress;
                        }

                        // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                        if(data.userSelectedType === 'R'){
                            // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                            // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                            if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                                extraAddr += data.bname;
                            }
                            // 건물명이 있고, 공동주택일 경우 추가한다.
                            if(data.buildingName !== '' && data.apartment === 'Y'){
                                extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                            }
                            // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                            if(extraAddr !== ''){
                                extraAddr = ' (' + extraAddr + ')';
                            }
                            // 조합된 참고항목을 해당 필드에 넣는다.
                            document.getElementById("sample6_extraAddress").value = extraAddr;
                        
                        } else {
                            document.getElementById("sample6_extraAddress").value = '';
                        }

                        // 우편번호와 주소 정보를 해당 필드에 넣는다.
                        document.getElementById('sample6_postcode').value = data.zonecode;
                        document.getElementById("sample6_address").value = addr;
                        // 커서를 상세주소 필드로 이동한다.
                        document.getElementById("sample6_detailAddress").focus();
                    }
                }).open();
            }
        </script>
        
        <br>
        <input type="submit" value="등록">

    </form>
    
    <br>
{% endblock %}

storeregister/templates/storeregister/store_result.html
{% extends 'base.html' %}
{% block content %}


    <form action="{% url 'storeregister:result' %}" method="get">
        <select name='query'>
            <option value="{{None}}">지역</option>
            <option value="GN">강남</option>
            <option value="SC">서초</option>
            <option value="YS">용산</option>
        </select>
        <input type="submit" name="" value="검색">
    </form>



    <p>검색 결과</p>


    {% for result in result.all %}
    <a href="{% url 'storeregister:detail' result.id %}">{{ result.store_title }}</a>
    {{ result.region }}
    <br>

    <br>
    <a href="{% url 'storeregister:register' %}">스토어 등록하기</a>

    {% endfor %}

{% endblock %}